[project]
name = "qwen-image-edit-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "diffusers[torch]",
    "modelscope>=1.29.1",
]

[tool.uv]
index-url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
